services:
  admin:
    build:
      context: .
    container_name: admin
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    environment:
        - SERVER_URL=:3000
        - WS_AUTH_TOKEN=${WS_AUTH_TOKEN:-token}
        - API_URL=${API_URL:-host.docker.internal:8083}
        - PASSWORD_FILE=${PASSWORD_FILE:-/tmp/password}
