- hosts: raspberry_water_system_admin
  tasks:
    - name: Stopping service if service exists
      with_first_found:
        - files:
            - /etc/systemd/system/water_system_admin.service
          skip: true
      shell: systemctl stop "{{ service_name }}"
      become: yes
    - name: Check that the binary file exists
      stat:
        path: "{{ binary_path }}"
      register: stat_result
    - name: Copy old binary file
      copy:
        src: "{{ binary_path }}"
        dest: "{{ binary_path }}_old"
        remote_src: yes
        force: yes
      when: stat_result.stat.exists == true
    - name: Upload binary file
      copy:
        src: assets/server
        dest: "{{ binary_path }}"
        mode: 0750
        force: yes
    - name: Create service directory if not exists
      file:
        path: "{{ systemd_path }}"
        state: directory
        owner: root
        group: root
        mode: 0755
      become: yes
    - name: Updload conf file
      template:
        src: config/water_system_admin.conf
        dest: /etc/systemd/system/water_system_admin.conf
        mode: 0644
        force: yes
      become: yes
    - name: Upload service file
      template:
        src: config/water_system_admin.service
        dest: /etc/systemd/system/water_system_admin.service
        mode: 0644
        force: yes
      become: yes
    - name: reload daemon service
      shell: systemctl daemon-reload
      become: yes
    - name: Enable service on boot
      shell: systemctl enable "{{ service_name }}"
      become: yes
    - name: Start service
      shell: systemctl restart "{{ service_name }}"
      become: yes
